version: '3'
services:
  postgres_scraping_service:
    image: my_postgres_image_v2:latest
    build:
      context: ./scraping  # PostgreSQL Dockerfile context 
      dockerfile: Dockerfile.postgres  # PostgreSQL image Dockerfile
    container_name: scraping_postgres_v2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data # postgres-data -> scraping_project_postgres-data would be a new volume # docker-postgresql_postgres-volume belongs to project which to 9302024 contains machadostudent aplication data
    restart: always
    ports:
      - "5434:5432" # (case1) host will be my linux for machadostudents java aplication (case2) host will be airflow for bimestral execution dag
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s  # Check each 10 seconds
      timeout: 5s    # Wait 5 seconds for the answer
      retries: 5     # Try 5 times before mark fail
      start_period: 60s  # Initial wait time before start check
    networks:
      - scraping_airflow_network

  scraping_service:
    image: my_scraping_image_v2:latest
    build:
      context: ./scraping  # Scraping Dockerfile context 
      dockerfile: Dockerfile  # Scraping image Dockerfile
    container_name: scraping_service_v2
    depends_on:
      postgres_scraping_service:
        condition: service_healthy
    networks:
      - scraping_airflow_network

networks:
  scraping_airflow_network:
    external: true

volumes:
  postgres-data: